Fuse safe integration
fuseio/safe-react pull request #1
Opened 2021-11-28 19:15 UTC by t0mcr8se

## TODO: 

- [X] Remove gnosis safe links in the footer
- [X] Remove intercom support message board
- [X] Change support links to fuseio 
- [X] Change safe-services api 
- [ ] Change logo
- [ ] Fix exchange price issue : add method to get gas price from oracle : https://api.fuseswap.com/api/v1/price/0x0BE9e53fd7EDaC9F859882AfdDa116645287C629
- [ ] Enable WalletConnect
- [ ] Enable Ledger 
- [ ] Delete other networks from src/config/networks
- [ ] Change color scheme

2021-12-02 10:32 UTC, leonprou commented on docker-compose.yml
> +      - 3002:3000
can you change this back?

2021-12-02 13:16 UTC, leonprou requested changes

2021-12-02 13:16 UTC, leonprou commented on package.json
> +    "@t0mcr8se/bnc-onboard": "1.35.6",
can you transfer the repo to fuseio and use our repo here?
I suppose I would need to publish this

2021-12-02 13:16 UTC, leonprou commented on package.json
> +    "build": "cross-env PUBLIC_URL=/ REACT_APP_APP_VERSION=$npm_package_version rescripts --max-old-space-size=8192 build",
no need to change this here, I handle this in the codebuild for S3 only

2021-12-02 13:16 UTC, leonprou commented on src/config/__tests__/config.test.ts
> +// const { mainnet, xdai } = networks
Can you make this work with fuse and fusespark?
Any issues this should not work

2021-12-02 13:22 UTC, t0mcr8se commented on package.json
> +    "@t0mcr8se/bnc-onboard": "1.35.6",
https://github.com/fuseio/onboard
this repo is ready to be deployed to npm, let me know when you deploy it so I can make the changes

2021-12-06 07:39 UTC, t0mcr8se commented on src/config/__tests__/config.test.ts
> +// const { mainnet, xdai } = networks
done

2021-12-06 11:43 UTC, leonprou commented on src/routes/CreateSafePage/steps/NameNewSafeStep.tsx
>            Ethereum blockchain. These funds cannot be accessed by Gnosis at any point.
Ethereum blockchain  -> Fuse Network

2021-12-06 11:43 UTC, leonprou commented on package.json
> +    "build": "cross-env REACT_APP_APP_VERSION=$npm_package_version rescripts  --max-old-space-size=8192 build",
please delete extra space :P

2021-12-06 11:43 UTC, leonprou approved these changes

2021-12-06 11:43 UTC, merged